// Generated by CoffeeScript 1.4.0
/*
#
#  Cria barras de redimencionamento
#  Quando redimencion passa um objeto
#  com os offsets da nova dimensão
#
*/

var BaseDOMManager, EditorControl, EditorView, LayerRedim, Main, Vector, ViewCenario, ace, main,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

LayerRedim = (function() {

  LayerRedim.BARRA_H = "url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAEAgMAAAC1h1SvAAAACVBMVEWxsbHPz8/t7e1xptKfAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QkNDTk7KlnoMAAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAHElEQVQI12OYGgoHIQxTQyPCRFsTw0QTMTkIZQCz3BCHwPjL5QAAAABJRU5ErkJggg==)";

  LayerRedim.BARRA_V = "url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAwAgMAAABLdDNWAAAACVBMVEWxsbHPz8/t7e1xptKfAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH3QkNDToNzs4uagAAAB1pVFh0Q29tbWVudAAAAAAAQ3JlYXRlZCB3aXRoIEdJTVBkLmUHAAAAF0lEQVQI12NYxRCKATMZHIli4WbDIAMAHbMP8YDVPsoAAAAASUVORK5CYII=)";

  function LayerRedim(divName, orientacao, position, callBack) {
    this.orientacao = orientacao;
    this.position = position;
    this.callBack = callBack;
    this.mouseMove = __bind(this.mouseMove, this);

    this.mouseUp = __bind(this.mouseUp, this);

    this.mouseDown = __bind(this.mouseDown, this);

    this.target = $("#" + divName);
    if (this.orientacao === void 0) {
      this.orientacao = "V";
    }
    if (this.position === void 0) {
      if (this.orientacao === 'V') {
        this.position = 'top';
      } else {
        this.position = 'left';
      }
    }
    this.barra = $(document.createElement('div'));
    this.barra.css({
      'position': 'absolute',
      'z-index': '1002'
    });
    if (this.orientacao === 'V') {
      this.barra.css({
        'background': '#ddf ' + LayerRedim.BARRA_V + " no-repeat center center",
        'cursor': 'w-resize'
      });
    } else {
      this.barra.css({
        'background': '#ddf ' + LayerRedim.BARRA_H + " no-repeat center center",
        'cursor': 'n-resize'
      });
    }
    this.barra.mousedown(this.mouseDown);
    this.rect = $(document.createElement('div'));
    this.rect.css({
      'position': 'absolute',
      'background': 'rgba(240,240,255,0.2)',
      'z-index': '1001',
      'display': 'none'
    });
    this.rect.mouseup(this.mouseUp);
    this.setupPosition();
    $(window.document.body).append(this.rect);
    $(window.document.body).append(this.barra);
  }

  LayerRedim.prototype.setupPosition = function() {
    var o;
    if (this.orientacao === 'V') {
      this.barra.width(4);
      this.barra.height(this.target.height());
    } else {
      this.barra.height(4);
      this.barra.width(this.target.width());
    }
    o = this.target.offset();
    switch (this.position) {
      case 'top':
        return this.barra.css({
          'top': o.top - 3,
          'left': o.left,
          'width': this.target.width()
        });
      case 'bottom':
        return this.barra.css({
          'top': this.target.offset().top + this.target.height() - 1,
          'left': o.left,
          'width': this.target.width()
        });
      case 'left':
        return this.barra.css({
          'left': this.target.offset().left - 3,
          'top': o.top,
          'height': this.target.height()
        });
      case 'right':
        return this.barra.css({
          'left': this.target.offset().left + this.target.width() - 1,
          'top': o.top,
          'height': this.target.height()
        });
    }
  };

  LayerRedim.prototype.showRec = function(x, y) {
    var o, r;
    o = this.target.offset();
    r = [o.left, o.top, o.left + this.target.width(), o.top + this.target.height()];
    if (this.orientacao === 'V') {
      if (this.position === 'left') {
        r[0] = x;
      } else {
        r[2] = x;
      }
    } else {
      if (this.position === 'top') {
        r[1] = y;
      } else {
        r[3] = y;
      }
    }
    /*
    		if @orientacao=='V'
    			if x<r[0]
    				r[0] = x
    				r[2] = x + @target.width()
    			else
    				r[2] = x
    		else
    			if y<r[1]
    				r[1] = y
    				r[3] = y + @target.height()
    			else
    				r[3] = y
    */

    return this.rect.css({
      'left': r[0],
      'top': r[1],
      'width': r[2] - r[0],
      'height': r[3] - r[1]
    });
  };

  LayerRedim.prototype.mouseDown = function(e) {
    var o;
    $(window).bind("mouseup", this.mouseUp).bind("mousemove", this.mouseMove);
    o = this.barra.offset();
    this.ox = e.pageX - o.left;
    this.oy = e.pageY - o.top;
    this.rect.css({
      'display': 'block'
    });
    this.showRec(e.pageX, e.pageY);
    return false;
  };

  LayerRedim.prototype.mouseUp = function(e) {
    var o;
    o = {
      left: this.rect.offset().left,
      top: this.rect.offset().top,
      right: this.rect.offset().left + this.rect.width(),
      bottom: this.rect.offset().top + this.rect.height(),
      width: this.rect.width(),
      height: this.rect.height(),
      target: this.target
    };
    $(window).unbind("mouseup", this.mouseUp).unbind("mousemove", this.mouseMove);
    this.rect.css({
      'display': 'none'
    });
    if (this.callBack !== void 0) {
      this.callBack(o);
    }
    return false;
  };

  LayerRedim.prototype.mouseMove = function(e) {
    if (this.orientacao === 'V') {
      this.barra.css('left', e.pageX - this.ox);
    } else {
      this.barra.css('top', e.pageY - this.oy);
    }
    this.showRec(e.pageX, e.pageY);
    return false;
  };

  return LayerRedim;

})();

BaseDOMManager = (function() {

  function BaseDOMManager() {
    this.getOffset = __bind(this.getOffset, this);

  }

  BaseDOMManager.prototype.injectCSS = function(target, css) {
    var i, _results,
      _this = this;
    _results = [];
    for (i in css) {
      _results.push((function(i) {
        return target.style[i] = css[i];
      })(i));
    }
    return _results;
  };

  BaseDOMManager.prototype.getOffset = function(ele) {
    var o;
    o = {
      x: 0,
      y: 0
    };
    while (ele) {
      if (ele.nodeName[0] !== '#') {
        o.x += ele.offsetLeft - ele.scrollLeft;
        o.y += ele.offsetTop - ele.scrollTop;
      }
      ele = ele.parentNode;
    }
    return o;
  };

  BaseDOMManager.prototype.addEvent = function(target, name, func) {
    if (target.attachEvent) {
      return target.attachEvent('on' + name, func);
    } else {
      return target.addEventListener(name, func);
    }
  };

  BaseDOMManager.prototype.ajaxRequest = function(url, callBack, type) {
    var nativeEval, request,
      _this = this;
    if (type === void 0) {
      type = 'text';
    }
    request = null;
    nativeEval = window['eval'];
    if (window.ActiveXObject) {
      try {
        request = new ActiveXObject("Msxml2.XMLHTTP");
      } catch (err) {

      }
      if (request === null) {
        try {
          request = new ActiveXObject("Microsoft.XMLHTTPP");
        } catch (e) {

        }
      }
    } else {
      try {
        request = new XMLHttpRequest();
      } catch (err) {

      }
    }
    if (request) {
      request.onreadystatechange = function() {
        if (request.readyState === 4) {
          if (request.status === 200) {
            if (type === 'json') {
              return callBack(nativeEval("(" + request.responseText + ")"));
            } else {
              return callBack(request);
            }
          }
        }
      };
      request.open("GET", url);
      request.send(null);
    }
    return request;
  };

  BaseDOMManager.prototype.parseDOM = function(xmlString) {
    var parser, xmlDoc;
    if (window.DOMParser) {
      parser = new DOMParser();
      xmlDoc = parser.parseFromString(xmlString, "text/xml");
    } else {
      xmlDoc = new ActiveXObject("Microsoft.XMLDOM");
      xmlDoc.async = false;
      xmlDoc.loadXML(xmlString);
    }
    return xmlDoc;
  };

  BaseDOMManager.prototype.trim = function(string) {
    return string.replace(/^\s+|\s+$/g, '');
  };

  return BaseDOMManager;

})();

ace = ace || null;

EditorView = (function(_super) {
  var Point;

  __extends(EditorView, _super);

  Point = (function() {

    Point.id = 0;

    Point.size = 4;

    function Point(x, y) {
      this.x = x;
      this.y = y;
      this._id = Point.id;
      Point.id += 1;
      this.links = [];
      this.id = null;
    }

    Point.prototype.connect = function(pt) {
      if (!this.hasLink(pt)) {
        this.links.push(pt);
        return pt.links.push(this);
      }
    };

    Point.prototype.hasLink = function(pt) {
      var j, v, _fn, _i, _len, _ref,
        _this = this;
      v = false;
      _ref = this.links;
      _fn = function(j) {
        if (j._id === pt._id) {
          return v = true;
        }
      };
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        j = _ref[_i];
        _fn(j);
      }
      return v;
    };

    Point.prototype.removeReferences = function() {
      var j, _i, _len, _ref, _results,
        _this = this;
      _ref = this.links;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        j = _ref[_i];
        _results.push((function(j) {
          return j.links.splice(j.links.indexOf(_this), 1);
        })(j));
      }
      return _results;
    };

    return Point;

  })();

  function EditorView(name, cenario) {
    var _this = this;
    this.cenario = cenario;
    this.load = __bind(this.load, this);

    this.salvar = __bind(this.salvar, this);

    this.getPontIndex = __bind(this.getPontIndex, this);

    this.mousemove = __bind(this.mousemove, this);

    this.mouseup = __bind(this.mouseup, this);

    this.mousedown = __bind(this.mousedown, this);

    this.alteraPointID = __bind(this.alteraPointID, this);

    this.resize = __bind(this.resize, this);

    this.canvas = document.getElementById(name);
    this.addEvent(this.canvas, 'mousedown', this.mousedown);
    this.addEvent(this.canvas, 'mouseup', this.mouseup);
    this.addEvent(this.canvas, 'mousemove', this.mousemove);
    this.isDown = false;
    this.isUp = false;
    this.isDraggin = false;
    this.isConnect = false;
    this.points = [];
    this.addEvent(document.getElementById('btSalvar'), 'click', this.salvar);
    this.addEvent(document.getElementById('btLoad'), 'click', this.load);
    this.editorStructControl = new EditorControl('mapStruct', '');
    this.codeResult = new EditorControl('dados', '{}', 'cobalt');
    this.codeResult.editor.renderer.setShowGutter(false);
    this.properties = new EditorControl('propertiesEditor', '{}');
    this.addEvent(window, 'resize', this.resize);
    this.addEvent(this.canvas, 'mouseover', function(e) {
      _this.codeResult.editor.blur();
      _this.editorStructControl.editor.blur();
      _this.properties.editor.blur();
      return _this.canvas.focus();
    });
    this.idField = document.getElementById('pointID');
    this.addEvent(this.idField, 'change', this.alteraPointID);
    this.defaultData();
    this.resize(null);
  }

  EditorView.prototype.resize = function(e) {
    if (this.canvas.parentElement !== null) {
      this.cenario.rec.width = this.canvas.width = this.canvas.parentElement.offsetWidth;
      return this.cenario.rec.height = this.canvas.height = this.canvas.parentElement.offsetHeight;
    }
  };

  EditorView.prototype.pointUnder = function(x, y) {
    var d, dd, i, point;
    dd = Point.size * Point.size;
    i = 0;
    while (i < this.points.length) {
      point = this.points[i];
      i += 1;
      d = (Math.pow(point.x - x, 2)) + (Math.pow(point.y - y, 2));
      if (d < dd) {
        return point;
      }
    }
    return null;
  };

  EditorView.prototype.alteraPointID = function(e) {
    console.log(e);
    if (this.last !== null && this.last !== void 0) {
      return this.last.id = this.idField.value;
    }
  };

  EditorView.prototype.mousedown = function(e) {
    var o, x, y;
    o = this.getOffset(this.canvas);
    x = e.x - o.x + this.cenario.rec.x;
    y = e.y - o.y + this.cenario.rec.y;
    this.idField.value = '';
    this.over = this.pointUnder(x, y);
    if (this.over !== null) {
      if (e.shiftKey) {
        this.isConnect = true;
      } else {
        this.isDraggin = true;
        if (this.over.id) {
          this.idField.value = this.over.id;
        }
      }
    }
    this.isDown = true;
    return false;
  };

  EditorView.prototype.mouseup = function(e) {
    var o, old, p, x, y;
    o = this.getOffset(this.canvas);
    x = e.x - o.x + this.cenario.rec.x;
    y = e.y - o.y + this.cenario.rec.y;
    this.isDown = false;
    if (this.isConnect) {
      p = this.pointUnder(x, y);
      console.log(p);
      if (p !== null) {
        this.over.connect(p);
      }
    } else {
      if (!this.isDraggin) {
        if (e.shiftKey) {

        } else {
          if (e.ctrlKey) {

          } else {
            old = this.last;
            this.last = new Point(x, y);
            this.points.push(this.last);
            if (old !== void 0 && old !== null) {
              this.last.connect(old);
            }
          }
        }
      } else {
        if (e.ctrlKey && this.over !== null) {
          this.points.splice(this.points.indexOf(this.over), 1);
          this.over.removeReferences();
          this.last = null;
        } else {
          this.last = this.over;
        }
        this.over.x = x;
        this.over.y = y;
        this.over = null;
      }
    }
    this.isDraggin = false;
    return this.isConnect = false;
  };

  EditorView.prototype.mousemove = function(e) {
    var o, x, y;
    if (this.isDraggin) {
      o = this.getOffset(this.canvas);
      x = e.x - o.x + this.cenario.rec.x;
      y = e.y - o.y + this.cenario.rec.y;
      this.over.x = x;
      this.over.y = y;
    }
    if (this.isConnect) {
      o = this.getOffset(this.canvas);
      this.conx = e.x - o.x + this.cenario.rec.x;
      this.cony = e.y - o.y + this.cenario.rec.y;
      e.preventDefault();
      return e.stopPropagation();
    }
  };

  EditorView.prototype.getPontIndex = function(pt) {
    var i;
    i = 0;
    while (i < this.points.length) {
      if (this.points[i].x === pt.x && this.points[i].y === pt.y) {
        return i;
      }
      i += 1;
    }
    return -1;
  };

  EditorView.prototype.defaultData = function() {
    this.points = [];
    this.editorStructControl.editor.setValue("{\n\"imagens\": [\n	[\"textures/cenarios/...\",0,0],\n	[\"textures/cenarios/...\",0,512],\n	[\"textures/cenarios/...\",768,0],\n	[\"textures/cenarios/...\",768,512]\n]\n}", 0);
    this.codeResult.editor.setValue('{}', 0);
    return this.properties.editor.setValue('{}', 0);
  };

  EditorView.prototype.salvar = function() {
    var pt, v, val, _fn, _i, _len, _ref,
      _this = this;
    v = "{\n";
    val = this.editorStructControl.editor.getValue();
    v += val.substring(val.indexOf("{") + 1, val.lastIndexOf("}") - 1);
    v += ",\n\"points\":[  \n";
    _ref = this.points;
    _fn = function(pt) {
      var j, _fn1, _j, _len1, _ref1;
      v += "\t{ \"x\":" + pt.x;
      v += ", \"y\":" + pt.y;
      if (pt.id !== null) {
        v += ", \"id\":\"" + pt.id + "\"";
      }
      v += ", \"links\":[ ";
      _ref1 = pt.links;
      _fn1 = function(j) {
        return v += _this.getPontIndex(j) + ",";
      };
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        j = _ref1[_j];
        _fn1(j);
      }
      v = v.substring(0, v.length - 1);
      return v += "]},\n";
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      pt = _ref[_i];
      _fn(pt);
    }
    v = v.substring(0, v.length - 2);
    v += "\n] }";
    this.codeResult.editor.setValue(v, 0);
    if (window.localStorage) {
      return window.localStorage.setItem("mapa", v);
    }
  };

  EditorView.prototype.load = function() {
    var d, data, i, pt, v, _eval, _fn, _fn1, _i, _j, _len, _len1, _ref, _ref1,
      _this = this;
    if (window.localStorage) {
      v = window.localStorage.getItem("mapa");
      this.codeResult.editor.setValue(v, 0);
      _eval = window["eval"];
      try {
        d = _eval("(" + v + ")");
        console.log(d);
        this.points.splice(0, this.points.length);
        _ref = d.points;
        _fn = function(pt) {
          var ppp;
          ppp = new Point(pt.x, pt.y);
          _this.points.push(ppp);
          if (pt.id) {
            return ppp.id = pt.id;
          }
        };
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          pt = _ref[_i];
          _fn(pt);
        }
        i = 0;
        _ref1 = d.points;
        _fn1 = function(pt) {
          var j, _fn2, _k, _len2, _ref2;
          _ref2 = pt.links;
          _fn2 = function(j) {
            return _this.points[i].links.push(_this.points[j]);
          };
          for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
            j = _ref2[_k];
            _fn2(j);
          }
          return i += 1;
        };
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          pt = _ref1[_j];
          _fn1(pt);
        }
        data = v.substring(0, v.indexOf(",\n\"points\":["));
        data += "\n}";
        this.editorStructControl.editor.setValue(data, 0);
        return this.cenario.addImagens(d.imagens);
      } catch (e) {
        alert("Não foi possível carregar os dados: \n" + e.message + "\n\nRestaurando defaults.");
        return this.defaultData();
      }
    } else {
      return a.innerHTML = "[Este navegador não suporta este recurso]";
    }
  };

  EditorView.prototype.render = function(cx) {
    var pas, point, _fn, _fn1, _i, _j, _len, _len1, _ref, _ref1, _results,
      _this = this;
    pas = 0;
    cx.strokeStyle = "#000";
    cx.lineWidth = 3;
    cx.font = "8px Courier";
    _results = [];
    while (pas < 2) {
      _ref = this.points;
      _fn = function(point) {
        var j, _fn1, _j, _len1, _ref1;
        cx.beginPath();
        cx.arc(point.x, point.y, Point.size, 0, Math.PI * 2);
        _ref1 = point.links;
        _fn1 = function(j) {
          cx.moveTo(point.x, point.y);
          return cx.lineTo(j.x, j.y);
        };
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          j = _ref1[_j];
          _fn1(j);
        }
        cx.stroke();
        return cx.closePath();
      };
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        point = _ref[_i];
        _fn(point);
      }
      cx.fillStyle = "#fff";
      _ref1 = this.points;
      _fn1 = function(point) {
        if (point.id !== null) {
          return cx.fillText(point.id, point.x, point.y - 4);
        }
      };
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        point = _ref1[_j];
        _fn1(point);
      }
      cx.fillStyle = "none";
      if (this.isConnect) {
        cx.strokeStyle = "#ff0";
        cx.beginPath();
        cx.moveTo(this.over.x, this.over.y);
        cx.lineTo(this.conx, this.cony);
        cx.stroke();
        cx.closePath();
      }
      cx.strokeStyle = "#fff";
      cx.lineWidth = 1;
      _results.push(pas += 1);
    }
    return _results;
    /*
    		# sombra
    		cx.shadownColor = "#000"
    		cx.shadowBlur = 2
    		cx.shadowOffsetX = 
    		cx.shadowOffsetY = 1
    */

  };

  return EditorView;

}).call(this, BaseDOMManager);

EditorControl = (function(_super) {

  __extends(EditorControl, _super);

  function EditorControl(name, data, theme) {
    this.data = data;
    document.getElementById(name).innerHTML = this.data;
    if (theme === void 0) {
      theme = 'monokai';
    }
    this.editor = ace.edit(name);
    this.editor.setTheme('ace/theme/' + theme);
    this.editor.getSession().setMode('ace/mode/json');
  }

  return EditorControl;

})(BaseDOMManager);

Main = (function(_super) {

  __extends(Main, _super);

  function Main() {
    this.mousemove = __bind(this.mousemove, this);

    this.mouseout = __bind(this.mouseout, this);

    this.mouseover = __bind(this.mouseover, this);

    this.render = __bind(this.render, this);

    this.keyup = __bind(this.keyup, this);

    this.keydown = __bind(this.keydown, this);

    this.start = __bind(this.start, this);
    this.addEvent(window, 'load', this.start);
  }

  Main.prototype.start = function(e) {
    this.cenario = new ViewCenario('mainCanvas', {
      imagens: [['textures/cenarios/01.jpg', 0, 0], ['textures/cenarios/02.jpg', 512, 0], ['textures/cenarios/03.jpg', 1024, 0], ['textures/cenarios/04.jpg', 1536, 0], ['textures/cenarios/05.jpg', 2048, 0], ['textures/cenarios/06.jpg', 2560, 0], ['textures/cenarios/07.jpg', 0, 512], ['textures/cenarios/08.jpg', 512, 512], ['textures/cenarios/09.jpg', 1024, 512], ['textures/cenarios/10.jpg', 1536, 512], ['textures/cenarios/11.jpg', 2048, 512], ['textures/cenarios/12.jpg', 2560, 512], ['textures/cenarios/13.jpg', 0, 1024], ['textures/cenarios/14.jpg', 512, 1024], ['textures/cenarios/15.jpg', 1024, 1024], ['textures/cenarios/16.jpg', 1536, 1024], ['textures/cenarios/17.jpg', 2048, 1024], ['textures/cenarios/18.jpg', 2560, 1024], ['textures/cenarios/19.jpg', 0, 1536], ['textures/cenarios/20.jpg', 512, 1536], ['textures/cenarios/21.jpg', 1024, 1536], ['textures/cenarios/22.jpg', 1536, 1536], ['textures/cenarios/23.jpg', 2048, 1536], ['textures/cenarios/24.jpg', 2560, 1536], ['textures/cenarios/25.jpg', 0, 2048], ['textures/cenarios/26.jpg', 512, 2048], ['textures/cenarios/27.jpg', 1024, 2048], ['textures/cenarios/28.jpg', 1536, 2048], ['textures/cenarios/29.jpg', 2048, 2048], ['textures/cenarios/30.jpg', 2560, 2048]]
    });
    this.cx = 0;
    this.cy = 0;
    this.addEvent(this.cenario.canvas, 'mousemove', this.mousemove);
    this.addEvent(this.cenario.canvas, 'mouseover', this.mouseover);
    this.addEvent(this.cenario.canvas, 'mouseout', this.mouseout);
    this.addEvent(window, 'keyup', this.keyup);
    this.addEvent(window, 'keydown', this.keydown);
    this.cenario.attackRenderModule(new EditorView('mainCanvas', this.cenario));
    this.cenario.attackRenderModule(this);
    return this.cenario.render();
  };

  Main.prototype.keydown = function(e) {
    if (e.keyCode >= 37 && e.keyCode <= 40) {
      this.keyCodeDown = e.keyCode;
      e.stopPropagation();
      e.preventDefault();
      return false;
    } else {
      return this.keyCodeDown = 0;
    }
  };

  Main.prototype.keyup = function(e) {
    return this.keyCodeDown = 0;
    /*
    		if ok
    			@cenario.focus @cx,@cy
    */

  };

  Main.prototype.render = function(cx) {
    var max, ok, x, y;
    ok = false;
    x = this.px;
    y = this.py;
    if (this.mouseOver) {
      if (x < 10) {
        this.cx -= 2;
        ok = true;
        if (this.cx < 0) {
          this.cx = 0;
        }
      }
      if (x > (this.cenario.canvas.width - 10)) {
        this.cx += 2;
        ok = true;
        max = this.cenario.size.width - this.cenario.canvas.width;
        if (this.cx > max) {
          this.cx = max;
        }
      }
      if (y < 10) {
        this.cy -= 2;
        ok = true;
        if (this.cy < 0) {
          this.cy = 0;
        }
      }
      if (y > (this.cenario.canvas.height - 10)) {
        this.cy += 2;
        ok = true;
        max = this.cenario.size.height - this.cenario.canvas.height;
        if (this.cy > max) {
          this.cy = max;
        }
      }
      if (this.keyCodeDown > 0) {
        ok = true;
        switch (this.keyCodeDown) {
          case 39:
            this.cx += 8;
            max = this.cenario.size.width - this.cenario.canvas.width;
            if (this.cx > max) {
              this.cx = max;
            }
            break;
          case 37:
            this.cx -= 8;
            if (this.cx < 0) {
              this.cx = 0;
            }
            break;
          case 38:
            this.cy -= 8;
            if (this.cy < 0) {
              this.cy = 0;
            }
            break;
          case 40:
            this.cy += 8;
            max = this.cenario.size.height - this.cenario.canvas.height;
            if (this.cy > max) {
              this.cy = max;
            }
        }
      }
      if (ok) {
        return this.cenario.focus(this.cx, this.cy);
      }
    }
  };

  Main.prototype.mouseover = function(e) {
    return this.mouseOver = true;
  };

  Main.prototype.mouseout = function(e) {
    return this.mouseOver = false;
  };

  Main.prototype.mousemove = function(e) {
    var o;
    o = this.getOffset(this.cenario.canvas);
    this.px = e.x - o.x;
    return this.py = e.y - o.y;
  };

  return Main;

})(BaseDOMManager);

window.main = main = new Main();

Vector = (function() {

  function Vector(x, y, z, w) {
    this.x = x;
    this.y = y;
    this.z = z;
    this.w = w;
    if (this.x === void 0) {
      this.x = 0;
    }
    if (this.y === void 0) {
      this.y = 0;
    }
    if (this.z === void 0) {
      this.z = 0;
    }
    if (this.w === void 0) {
      this.w = 1;
    }
  }

  Vector.prototype.add = function() {};

  return Vector;

})();

ViewCenario = (function() {
  var ViewImage, ViewRect;

  ViewRect = (function() {

    function ViewRect(x, y, width, height) {
      this.x = x;
      this.y = y;
      this.width = width;
      this.height = height;
      if (this.x instanceof HTMLCanvasElement) {
        this.width = this.x.width;
        this.height = this.x.height;
        this.x = 0;
        this.y = 0;
      }
    }

    ViewRect.prototype.colide = function(rec) {
      var c;
      c = false;
      if (rec.x < (this.x + this.width)) {
        if ((rec.x + rec.width) >= this.x) {
          if (rec.y < (this.y + this.height)) {
            if ((rec.y + rec.height) >= this.y) {
              c = true;
            }
          }
        }
      }
      return c;
    };

    return ViewRect;

  })();

  ViewImage = (function() {

    function ViewImage(src, x, y, parent) {
      var _this = this;
      this.x = x;
      this.y = y;
      this.parent = parent;
      this.image = new Image();
      this.width = 0;
      this.height = 0;
      this.visible = false;
      this.isLoaded = false;
      this.image.src = src;
      this.image.onload = function(e) {
        _this.width = _this.image.width;
        _this.height = _this.image.height;
        return _this.parent.computeSize();
      };
    }

    return ViewImage;

  })();

  function ViewCenario(name, data) {
    this.render = __bind(this.render, this);
    this.canvas = document.getElementById(name);
    this.rec = new ViewRect(this.canvas);
    this.background = "#000";
    this.dirty = true;
    this.renderModules = [];
    this.size = {
      width: 800,
      height: 800
    };
    this.addImagens(data.imagens);
  }

  ViewCenario.prototype.addImagens = function(list) {
    var i, _i, _len, _results,
      _this = this;
    this.imagens = [];
    _results = [];
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      i = list[_i];
      _results.push((function(i) {
        var img;
        console.log(i);
        img = new ViewImage(i[0], i[1], i[2], _this);
        return _this.imagens.push(img);
      })(i));
    }
    return _results;
  };

  ViewCenario.prototype.attackRenderModule = function(rm) {
    return this.renderModules.push(rm);
  };

  ViewCenario.prototype.computeSize = function() {
    var h, i, w, _fn, _i, _len, _ref,
      _this = this;
    w = 0;
    h = 0;
    _ref = this.imagens;
    _fn = function(i) {
      var x, y;
      x = i.x + i.image.width;
      y = i.y + i.image.height;
      if (x > w) {
        w = x;
      }
      if (y > h) {
        return h = y;
      }
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      _fn(i);
    }
    this.size.width = w;
    return this.size.height = h;
  };

  ViewCenario.prototype.focus = function(x, y) {
    var maxH, maxW;
    if (x < 0) {
      x = 0;
    }
    if (y < 0) {
      y = 0;
    }
    maxW = this.size.width - this.rec.width;
    maxH = this.size.height - this.rec.height;
    if (x > maxW) {
      x = maxW;
    }
    if (y > maxH) {
      y = maxH;
    }
    this.rec.x = x;
    return this.rec.y = y;
  };

  ViewCenario.prototype.calcViews = function(cx) {
    var v, _i, _len, _ref, _results,
      _this = this;
    _ref = this.imagens;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      v = _ref[_i];
      _results.push((function(v) {
        if (_this.rec.colide(v)) {
          v.visible = true;
          return cx.drawImage(v.image, v.x, v.y);
        } else {
          return v.visible = false;
        }
      })(v));
    }
    return _results;
  };

  ViewCenario.prototype.render = function() {
    var cx, module, _fn, _i, _len, _ref,
      _this = this;
    if (!this.dirty) {
      return;
    }
    cx = this.canvas.getContext('2d');
    cx.setTransform(1, 0, 0, 1, 0, 0);
    cx.fillStyle = this.background;
    cx.fillRect(0, 0, this.canvas.width, this.canvas.height);
    cx.setTransform(1, 0, 0, 1, -this.rec.x, -this.rec.y);
    this.calcViews(cx);
    _ref = this.renderModules;
    _fn = function(module) {
      return module.render(cx);
    };
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      module = _ref[_i];
      _fn(module);
    }
    return window.setTimeout(this.render, 40);
  };

  return ViewCenario;

})();

/*
	constructor: (name) ->
		@canvas = document.getElementById name

		@heightMap = new Image()
		@heightMap.onload = @mapLoaded
		@loadeds = 0

		@heightMap.src = 'textures/cen1.png'

		@addEvent window, 'keydown', @keydown
		@x = Math.round @canvas.width / 2
		@y = Math.round @canvas.height / 2


	mapLoaded: (e) =>
		console.log e
		@loadeds += 1
		if @loadeds == 1
			@render()

	keydown: (e) =>
		#console.log e.keyCode
		switch e.keyCode
			when 37 #esq
				@x -= 2
			when 38 #up
				@y -= 2
			when 39 #dir
				@x += 2
			when 40 #down
				@y += 2
		e.preventDefault()
		e.stopPropagation()
		false

	render: () =>
		cx = @canvas.getContext '2d'
		cx.drawImage @heightMap,0,0

		cx.beginPath()
		cx.strokeStyle = '#bb0'
		cx.lineWidth = 1
		cx.arc @x,@y, 3, 0, 2*Math.PI
		cx.stroke()


		

		window.setTimeout @render, 50
*/

